-- Licensed under the Open Software License version 3.0

_G.aliases = {}
aliases["cl"] = "clear"
aliases["prune"] = "clear"
aliases["purge"] = "clear"
aliases["whois"] = "user"
aliases["die"] = "disconnect"
aliases["dc"] = "disconnect"
aliases["p"] = "play"
aliases["s"] = "pause"
aliases["stop"] = "pause"
aliases["st"] = "shorten"
aliases["0x0"] = "shorten"
aliases["lua"] = "eval"
aliases["exec"] = "eval"
aliases["av"] = "avatar"
aliases["avi"] = "avatar"
aliases["cutie"] = "cute"
aliases["c"] = "cute"
aliases["cm"] = "cute"
aliases["wsg"] = "webm"
aliases["f0ck"] = "webm"
aliases["w"] = "webm"